// @generated by scripts/generate_api_types.py
// Source of truth: aidm_server/api_type_contract.py
// Do not edit manually.

export type JsonRecord = Record<string, unknown>

export type RaceSource = 'curated' | 'custom' | 'template' | 'imported'

export type RaceBalanceMetadata = { budget: number; spent: number; tier: 'weak' | 'standard' | 'strong' | 'overpowered'; warnings?: string[] }

export type RaceVisualMetadata = JsonRecord

export type RacePhysicalMetadata = { averageHeight: string; averageWeight: string }

export type RaceDefinition = JsonRecord & { id: string; version: number; name: string; source: RaceSource; descriptionShort: string; descriptionLong: string; aliases: string[]; tags: string[]; size: string; baseSpeed: number; visual: RaceVisualMetadata; originStory: string; physical: RacePhysicalMetadata; languages: string[]; commonProficiencies: string[]; friendlyWith: string[]; waryOf: string[]; traits: JsonRecord[]; aiNarrationHints: string[]; roleplayHooks: string[]; recommendedClasses: string[]; difficulty: string; balance: RaceBalanceMetadata; approvalStatus?: string; parentRaceId?: string | null; workspaceId?: string; createdByAccountId?: number | null; createdByUsername?: string | null; createdByDisplayName?: string | null; createdAt?: string | null; updatedAt?: string | null }

export type RaceSummary = {
  id: string
  version: number
  name: string
  source: RaceSource
  descriptionShort: string
  aliases: string[]
  tags: string[]
  size: string
  baseSpeed: number
  visual: RaceVisualMetadata
  originStory: string
  physical: RacePhysicalMetadata
  languages: string[]
  commonProficiencies: string[]
  friendlyWith: string[]
  waryOf: string[]
  traits: string[]
  recommendedClasses: string[]
  difficulty: string
  balance: RaceBalanceMetadata
  approvalStatus?: string
  parentRaceId?: string | null
  workspaceId?: string
  createdByAccountId?: number | null
  createdByUsername?: string | null
  createdByDisplayName?: string | null
  createdAt?: string | null
  updatedAt?: string | null
}

export type CharacterRaceSelection = {
  raceId: string
  raceName: string
  source: RaceSource
  customRaceDefinition?: RaceDefinition
  selectedOptions?: JsonRecord
}

export type RaceListResponse = { races: RaceSummary[] }

export type CustomRaceGenerateResponse = { draftRace: RaceDefinition; balanceAnalysis: RaceBalanceMetadata; warnings: string[]; generationSource: string; generationMode: 'canon' | 'balanced' }

export type CustomRaceSaveResponse = { race: RaceDefinition; summary: RaceSummary }

export type CreatureSource = 'core_bestiary' | 'campaign_pack' | 'region_bestiary' | 'generated' | 'generated_variant' | 'user_custom' | 'evolved'

export type BestiaryScope = 'core' | 'campaign' | 'region' | 'session'

export type CreatureBalanceMetadata = JsonRecord & { estimatedTier: string; targetTier: string; estimatedDamagePerRound: number; estimatedDurability: number; estimatedControlStrength: number; warnings: string[]; balanceAdjustments?: string[]; reviewed: boolean }

export type CreatureDefinition = JsonRecord & { id: string; version: number; name: string; source: CreatureSource; descriptionShort: string; descriptionLong: string; creatureType: string; visualTags: string[]; level: number; challengeTier: string; size: string; stats: JsonRecord; movement: JsonRecord; senses: JsonRecord; abilities: JsonRecord[]; behavior: JsonRecord; aiNarrationHints: string[]; balance: CreatureBalanceMetadata }

export type BestiaryEntryPayload = {
  bestiary_entry_id: number | null
  workspace_id: string
  campaign_id: number | null
  session_id: number | null
  scope: BestiaryScope | string
  creature_id: string
  version: number
  name: string
  source: CreatureSource | string
  persistence: string
  region_id: string | null
  location_ids: string[]
  faction_ids: string[]
  tags: string[]
  creature: CreatureDefinition
  balance: JsonRecord
  created_because: string | null
  base_creature_id: string | null
  variant_reason: string | null
  created_at_turn: number | null
  created_by_model: string | null
  created_at: string | null
  updated_at: string | null
}

export type BestiaryListResponse = { campaign_id?: number; region_id?: string; entries: BestiaryEntryPayload[] | CreatureDefinition[] }

export type CreatureResolutionResult = { creature: CreatureDefinition; source: CreatureSource | string; resolutionMethod: string; matchScore?: number | null; generated: boolean; savedToBestiary: boolean; notes: string[]; debug?: JsonRecord }

export type CreatureGenerateResponse = { creature: CreatureDefinition; generationSource: string; balance: JsonRecord }

export type CreatureBalanceResponse = { balance: CreatureBalanceMetadata; scaledCreature: CreatureDefinition }

export type CreatureEvolveResponse = { creature: CreatureDefinition; entry?: BestiaryEntryPayload | null }

export type CampaignPackGenerateResponse = { campaign_id: number; creatures: CreatureDefinition[]; entries: BestiaryEntryPayload[] }

export type CombatIntentPlanResponse = { intentPlan: JsonRecord; combat: JsonRecord }

export type SessionCombatResponse = { combat: JsonRecord | null; validation?: JsonRecord; appliedChanges?: JsonRecord[]; endReason?: string | null }

export type CombatDebugEventsResponse = { events: JsonRecord[] }

export type TurnFeedbackReport = {
  feedback_id: number
  session_id: number
  turn_id: number | null
  feedback_type: string
  category: string | null
  coherence_score: number
  notes: string | null
  provider: string | null
  model: string | null
  turn_status: string | null
  turn_latency_ms: number | null
  created_at: string | null
}

export type BadTurnFeedbackResponse = { feedback: TurnFeedbackReport }

export type BetaIncidentsResponse = { incidents: JsonRecord[]; summary: { failed_turn_count: number; failed_canon_job_count: number; bad_turn_report_count: number; telemetry_incident_count: number }; limit: number }

export type BetaAuditsResponse = { state_mutations: JsonRecord[]; operator_actions: JsonRecord[]; summary: { state_mutation_count: number; operator_action_count: number }; limit: number }

export type World = {
  world_id: number
  name: string
  description: string | null
  created_at: string | null
}

export type Campaign = {
  campaign_id: number
  title: string
  description: string | null
  world_id: number
  world_name: string | null
  created_at: string | null
  updated_at: string | null
  status: string
  is_archived: boolean
  current_quest: string | null
  location: string | null
  session_count: number
  latest_session_id: number | null
  latest_activity_at: string | null
}

export type SessionSummary = {
  session_id: number
  campaign_id: number
  created_at: string | null
  status: string
  deleted_at: string | null
  updated_at: string | null
  latest_activity_at: string | null
  display_name: string
  turn_count: number
  latest_summary: string
  is_archived: boolean
  state_snapshot: JsonRecord | null
}

export type SessionImportResponse = {
  imported: boolean
  session_id: number
  session: SessionSummary
  counts: { turn_events: number; projected_log_entries: number; log_entries: number; session_state: number }
}

export type CampaignWorkspace = {
  campaign: Campaign
  sessions: SessionSummary[]
  players: Player[]
  maps: MapItem[]
  segments: CampaignSegment[]
  summary: { session_count: number; player_count: number; map_count: number; segment_count: number; latest_session_id: number | null; latest_activity_at: string | null }
  has_more: { sessions: boolean; players: boolean; maps: boolean; segments: boolean }
  next_cursor: { sessions: number | null; players: number | null; maps: number | null; segments: number | null }
  limits: { sessions: number | null; players: number | null; maps: number | null; segments: number | null }
}

export type AccountWorkspace = {
  workspace_id: string
  workspace_name?: string
  table_name?: string
  access_mode?: 'password' | 'token' | 'configured' | 'unknown'
  workspace_role: string
  is_workspace_admin: boolean
  created_at: string | null
  updated_at: string | null
}

export type Account = {
  account_id: number
  username: string
  first_name: string
  last_name: string
  display_name: string
  workspace_id: string | null
  workspace_role: string | null
  is_workspace_admin: boolean
  requires_password_setup: boolean
  workspaces: AccountWorkspace[]
}

export type AccountSession = {
  account: Account
  account_token: string
  account_token_transport?: string | null
  workspace_id: string | null
  workspace_role: string | null
  is_workspace_admin: boolean
  claimed_player_ids: number[]
  workspaces: AccountWorkspace[]
  workspace_token?: string | null
}

export type SessionLogEntry = {
  id: number
  message: string
  entry_type: string
  metadata: JsonRecord
  timestamp: string | null
}

export type SessionLogResponse = {
  session_id: number
  limit?: number
  has_more?: boolean
  next_cursor?: number | null
  entries: SessionLogEntry[]
}

export type TurnEventPayload = {
  event_id: number
  session_id: number
  campaign_id: number
  turn_id: number | null
  player_id: number | null
  event_type: string
  payload: JsonRecord
  created_at: string | null
}

export type SessionEventsResponse = {
  session_id: number
  limit?: number
  has_more?: boolean
  next_cursor?: number | null
  events: TurnEventPayload[]
}

export type SessionState = {
  session_id: number
  campaign_id: number
  current_location: string | null
  current_quest: string | null
  rolling_summary: string
  active_segments: unknown[]
  memory_snippets: unknown[]
  state_snapshot: JsonRecord | null
  updated_at: string | null
}

export type Player = {
  player_id: number
  workspace_id: string
  account_id: number | null
  username: string | null
  campaign_id: number | null
  name: string
  character_name: string
  race: string | null
  race_selection?: CharacterRaceSelection | null
  sex: string | null
  profile_image: string
  class_: string | null
  char_class: string | null
  level: number
  created_at: string | null
  updated_at: string | null
}

export type PlayerDetail = {
  player_id: number
  workspace_id: string
  account_id: number | null
  username: string | null
  campaign_id: number | null
  name: string
  character_name: string
  race: string | null
  race_selection?: CharacterRaceSelection | null
  sex: string | null
  profile_image: string
  class_: string | null
  char_class: string | null
  level: number
  created_at: string | null
  updated_at: string | null
  stats: unknown
  inventory: unknown
  character_sheet: unknown
  derived?: JsonRecord
}

export type PlayerEquipmentUpdateResponse = PlayerDetail & { snapshot_changed: boolean; equipment_update: JsonRecord }

export type MapItem = {
  map_id: number
  world_id: number | null
  campaign_id: number | null
  title: string
  description: string | null
  map_data: JsonRecord
  created_at: string | null
  updated_at: string | null
}

export type CampaignSegment = {
  segment_id: number
  campaign_id: number
  title: string
  description: string | null
  trigger_condition: string | null
  tags: string | null
  external_id: string | null
  source: string
  source_pack_id: string | null
  metadata: JsonRecord
  is_triggered: boolean
  created_at: string | null
  updated_at: string | null
}
