// @generated by scripts/generate_api_types.py
// Source of truth: aidm_server/api_type_contract.py
// Do not edit manually.

export type JsonRecord = Record<string, unknown>

export type World = {
  world_id: number
  name: string
  description: string | null
  created_at: string | null
}

export type Campaign = {
  campaign_id: number
  title: string
  description: string | null
  world_id: number
  world_name: string | null
  created_at: string | null
  updated_at: string | null
  status: string
  is_archived: boolean
  current_quest: string | null
  location: string | null
  session_count: number
  latest_session_id: number | null
  latest_activity_at: string | null
}

export type SessionSummary = {
  session_id: number
  campaign_id: number
  created_at: string | null
  status: string
  deleted_at: string | null
  updated_at: string | null
  latest_activity_at: string | null
  display_name: string
  turn_count: number
  latest_summary: string
  is_archived: boolean
  state_snapshot: JsonRecord | null
}

export type SessionImportResponse = {
  imported: boolean
  session_id: number
  session: SessionSummary
  counts: { turn_events: number; projected_log_entries: number; log_entries: number; session_state: number }
}

export type CampaignWorkspace = {
  campaign: Campaign
  sessions: SessionSummary[]
  players: Player[]
  maps: MapItem[]
  segments: CampaignSegment[]
  summary: { session_count: number; player_count: number; map_count: number; segment_count: number; latest_session_id: number | null; latest_activity_at: string | null }
  has_more: { sessions: boolean; players: boolean; maps: boolean; segments: boolean }
  next_cursor: { sessions: number | null; players: number | null; maps: number | null; segments: number | null }
  limits: { sessions: number | null; players: number | null; maps: number | null; segments: number | null }
}

export type SessionLogEntry = {
  id: number
  message: string
  entry_type: string
  metadata: JsonRecord
  timestamp: string | null
}

export type SessionLogResponse = {
  session_id: number
  limit?: number
  has_more?: boolean
  next_cursor?: number | null
  entries: SessionLogEntry[]
}

export type TurnEventPayload = {
  event_id: number
  session_id: number
  campaign_id: number
  turn_id: number | null
  player_id: number | null
  event_type: string
  payload: JsonRecord
  created_at: string | null
}

export type SessionEventsResponse = {
  session_id: number
  limit?: number
  has_more?: boolean
  next_cursor?: number | null
  events: TurnEventPayload[]
}

export type SessionState = {
  session_id: number
  campaign_id: number
  current_location: string | null
  current_quest: string | null
  rolling_summary: string
  active_segments: unknown[]
  memory_snippets: unknown[]
  state_snapshot: JsonRecord | null
  updated_at: string | null
}

export type Player = {
  player_id: number
  workspace_id: string
  campaign_id: number | null
  name: string
  character_name: string
  race: string | null
  sex: string | null
  profile_image: string
  class_: string | null
  char_class: string | null
  level: number
  created_at: string | null
  updated_at: string | null
}

export type PlayerDetail = {
  player_id: number
  workspace_id: string
  campaign_id: number | null
  name: string
  character_name: string
  race: string | null
  sex: string | null
  profile_image: string
  class_: string | null
  char_class: string | null
  level: number
  created_at: string | null
  updated_at: string | null
  stats: unknown
  inventory: unknown
  character_sheet: unknown
}

export type MapItem = {
  map_id: number
  world_id: number | null
  campaign_id: number | null
  title: string
  description: string | null
  map_data: JsonRecord
  created_at: string | null
  updated_at: string | null
}

export type CampaignSegment = {
  segment_id: number
  campaign_id: number
  title: string
  description: string | null
  trigger_condition: string | null
  tags: string | null
  is_triggered: boolean
  created_at: string | null
  updated_at: string | null
}
