from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from aidm_server.api_type_contract import API_TYPE_CONTRACTS, TypeContract  # noqa: E402

OUTPUT = ROOT / 'aidm_frontend' / 'src' / 'apiContract.generated.ts'


def _render_contract(contract: TypeContract) -> str:
    if contract.alias is not None:
        return f'export type {contract.name} = {contract.alias}\n'

    lines = [f'export type {contract.name} = {{']
    for field in contract.fields:
        optional = '?' if field.optional else ''
        lines.append(f'  {field.name}{optional}: {field.ts_type}')
    lines.append('}\n')
    return '\n'.join(lines)


def render_types() -> str:
    chunks = [
        '// @generated by scripts/generate_api_types.py',
        '// Source of truth: aidm_server/api_type_contract.py',
        '// Do not edit manually.',
        '',
    ]
    chunks.extend(_render_contract(contract) for contract in API_TYPE_CONTRACTS)
    return '\n'.join(chunks).rstrip() + '\n'


def main() -> int:
    OUTPUT.write_text(render_types(), encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
